### ISSUE TITLE
Include CSS in dist

### ISSUE THREAD

**Issue by cgatian** [chrisweb/rehype-github-alerts#10]
Would it be possible to ship the CSS stylesheet as a part of the package?

I can copy-paste it myself, but it might be nice to include it in the bundle.

**Comment by chrisweb** [comment]
@cgatian we had a similar discussion not so long where I talked about the pro and cons I see in adding a CSS to the package itself: https://github.com/chrisweb/rehype-github-alerts/discussions/9#discussioncomment-11284610

So tldr I'm not convinced this would be an improvement

If you have to copy paste the CSS from a Readme that has quite good visibility (gets seen easily by people wanting to use the package) versus having the CSS in a folder in the package itself (where it might get overlooked and would probably need to get mentioned in the readme anyway), is that really better? I mean a CSS file would not get imported, it would just be there in some folder and then the dev would need to copy paste the CSS from that file to his own CSS (or copy and eventually transform it into one of the many options you have when it comes to applying CSS / styling in a Nextjs/Reatc project)

**Comment by cgatian** [comment]
Yeah, I was just thinking that if the structure of the DOM this plugin outputs changes, it might be nice to keep the styles in lockstep.

Frameworks sometimes [rely on a setup](https://panda-css.com/docs/installation/nextjs#configure-the-entry-css-with-layers) step to include their CSS within your page, so I don't think this is asking for something out of the ordinary. I'm not here to try to convince you; I think what you have works. This is just a suggestion.
